AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple sample to receive events from a Tenovos Platform SNS topic, to catch Tenovos events from a Tenovos Integration account
Globals:
  Function:
    Timeout: 3

Resources:
  TenovosEventListenerReference:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tenovos-integ-reference.handler
      FunctionName: tenovos-integ-reference-_INTEGRATOR_COMPANY_-_INTEGRATOR_INDIVIDUAL_INITIALS_
      Timeout: 75
      Runtime: nodejs12.x
      Role: _IAM_ROLE_
      Environment:
        Variables:
          TNVS_ACCESS_KEY_ID: _TNVS_ACCESS_KEY_ID_
          TNVS_SECRET_ACCESS_KEY: _TNVS_SECRET_ACCESS_KEY_
          TNVS_REFERENCE_SLACK_WEB_HOOK: _TNVS_REFERENCE_SLACK_WEB_HOOK_
          TNVS_REST_API_KEY: _TNVS_REST_API_KEY_
          TNVS_USER_POOL_ID: _TNVS_USER_POOL_ID_
          TNVS_CLIENT_ID: _TNVS_CLIENT_ID_
          TNVS_USERNAME: _TNVS_USERNAME_
          TNVS_PASSWORD: _TNVS_PASSWORD_
      Events:
        TenovosEventListenerApiReference:
          Type: Api
          Properties:
            Path: /tenovos-integ-reference-_INTEGRATOR_COMPANY_-_INTEGRATOR_INDIVIDUAL_INITIALS_
            Method: ANY
