AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cust-pantry-request-created-handler

  SAM Template for cust-pantry-request-created-handler

Globals:
  Function:
    Timeout: 3

Resources:
  CustPantryRequestCreatedHandler:
    DependsOn: CustPantryCreateDownloadRequestProcessor
    Type: AWS::Serverless::Function
    Properties:
      Handler: cust-pantry-request-created-handler.handler
      FunctionName: cust-pantry-request-created-handler
      Timeout: 75
      Runtime: nodejs12.x
      Policies:
        - AdministratorAccess
      Environment:
        Variables:
          REVIEWER_SECURITY_TEMPLATE: '{{resolve:ssm:/config/download-request/reviewer-security-template:1}}'
          SENDER_EMAIL: '{{resolve:ssm:/config/sender-email:1}}'
          CC_MAILING_LIST: '{{resolve:ssm:/config/download-request/mailing-list:1}}'
          SUBMITTED_BY_METADATA_DEFINITION_ID: '{{resolve:ssm:/config/download-request/submitted-by-metadata-definition-id:1}}'
      Events:
        CustCtcSkuSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CustPantryCreateDownloadRequestProcessor.Arn
            BatchSize: 10

  CustPantryCreateDownloadRequestProcessor:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: cust-pantry-create-download-request-processor_SQS
      VisibilityTimeout: 600
      MessageRetentionPeriod: 3600